### ISSUE TITLE
Add Patient Name to the HC app

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#47]

**Comment by ifoche** [comment]
@ppagalday I'm considering that you want this one for the next maintenance release as you added a milestone. I've cleaned all the milestones from the previous issues in backlog column, to start from scratch the labeling. So please, if you want an issue to be considered for the next maintenance release, just add the **0.4** milestone (0.5 is reserved for a hypothetical future normal release) and I will start trying to replicate it and ask you as many questions as needed in order to assess the level of effort. 

So regarding this issue. Where should we introduce this new question? before "Age of patient" is ok?

**Comment by ppagalday** [comment]
@ifoche thanks! Yes exactly, will do, before the Age will work. I will check the other issues with Jose see how we replicate them (the bugs)
