### ISSUE TITLE
Add Tested or RDT Stock out to first VMW screen

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/CNMApp#5]
## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot267883270.jpg)
## Device Info
```
Time Stamp: 2018-03-30T11:33:04 UTC
App Version: 0.3.0 (52)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-G930F
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ppagalday** [comment]
We would like to have a similar screen as HC app to detect RDT stock out. The first option is to make the first screen: Tested or RDT Stock out. There is no need to add other reasons for not tested right now, but if it is easier to use same flow as in HC app up to you to decide the best way.

**Comment by ifoche** [comment]
@ppagalday, looks like a modification of what was agreed, but we would be happy to implement something like exactly the diagnosis method screen from HC offering only:
- RDT
- Not tested.

This way we would only need to add the DE server side and the question app side removing the undesired option. Would this work?

**Comment by ppagalday** [comment]
@ifoche after talking with Jose, he told me he forgot to mention that to you for VMWs. Would it be feasible to instead of saying not tested say RDT stock out? The main reason is we would like to gather whether the RDTs are out, so we only have a reason for not tested, but just to do make it clear to health workers.

**Comment by ifoche** [comment]
@ppagalday. Ok, so we would be talking about a new DE let's say "MCS - Stockout" with DE form name "RDT stock out?" associated to the "Malaria - VMW program" with a new optionSet let's say "Stockout" with options:
- Tested
- RDT Stock out

That's in the server. In the Android device we would need to create the question also in the embedded metadata with their answers and we would need to design images for those 2 options in order to introduce them also.

Is that it?

**Comment by ppagalday** [comment]
@ifoche Exactly, that sounds great

**Comment by ppagalday** [comment]
Sorry to multiple comments, clicked sent before finishing. The images for RDT Stock out are used in the HC in the DE reasons for not tested so we can re-utilize that one.
